export interface Plot {
    id: number,
    user_id: number,
    empresa_id?: number | null,
    nombre_parcela: string,
    apodo_parcela: string,
    provincia: string,
    municipio: string,
    poligono: number,
    parcela: number,
    superficie_ha: number,
    referencia_catastro: string,
    observaciones: string,
    lat: number,
    lng: number,
    x: number,
    y: number,
    wkt: string,
    trabajos: Array<any>
}